version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.11 /usr/local/share/virtualenvs/tap-linkedin-ads
            source /usr/local/share/virtualenvs/tap-linkedin-ads/bin/activate
            uv pip install -U 'pip<19.2' 'setuptools<51.0.0'
            uv pip install .[dev]
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-linkedin-ads/bin/activate
            pylint tap_linkedin_ads -d C,R,W
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_linkedin_ads/schemas/*.json
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-linkedin-ads/bin/activate
            uv pip install pytest coverage parameterized
            coverage run -m pytest tests/unittests
            coverage html
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: htmlcov
      - run:
          when: always
          name: 'Integration Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            uv pip install --upgrade awscli
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
            source dev_env.sh
            run-test --tap=tap-linkedin-ads tests
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 19 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
